name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

  testes:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Testes Unitarios
        run: mvn test

  release:
    name: Criação da release
    runs-on: ubuntu-latest
    needs: [testes]
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/efengv1:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/efengv1:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "efengv1-api-prd"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: "index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/efengv1:latest"
